### ISSUE TITLE
Scrolling up with mouse whell does not work properly

### ISSUE THREAD

**Issue by rizkyilhampra** [Aasim-A/scrollEOF.nvim#11]
How to reproduce :
1. go to end of line
2. do mouse whell up

is it actual behavior i can't use mouse whell especially mouse whell up properly with this plugin? 

anyway thanks for the plugin

-- EDIT 
The issue happens when my cursor is at the end of the line and I scroll up with mouse.

**Comment by Aasim-A** [comment]
Hi @rizkyilhampra , sorry for not replying for this long as I was busy. I have tried to reproduce the problem but didn't notice anything odd. can you post a gif or a video showing the issue? Also, can you post your neovim verison?

**Comment by rizkyilhampra** [comment]
thank you for the update. it works great now.
