### ISSUE TITLE
cursor misalignment in normal mode when vim.o.smoothscroll = true

### ISSUE THREAD

**Issue by Espacio-root** [Aasim-A/scrollEOF.nvim#18]
As the title states, the cursor sometimes gets misaligned when the vim option "smoothscroll" is set to true

Uploading output.mp4…

**Comment by Espacio-root** [comment]
https://github.com/Aasim-A/scrollEOF.nvim/assets/118763335/2c6d5927-3651-4f41-9a0a-8471121745a9

**Comment by Aasim-A** [comment]
Hi, can you post your neovim version?

**Comment by Aasim-A** [comment]
I was unable to reproduce the issue. Is there another plugin that's causing the issue?

**Comment by Espacio-root** [comment]
NVIM v0.11.0-dev-313+gfc9b70826e
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189

**Comment by Aasim-A** [comment]
Still unable to reproduce. Please provide a minimal reproducible setup.
