### ISSUE TITLE
Off by one error compared to scrolloff

### ISSUE THREAD

**Issue by DanielPower** [Aasim-A/scrollEOF.nvim#6]
Thank you for this plugin. It makes Copilot much more helpful, as virtual text can be seen on lines beyond EOF.

I've noticed a minor issue where the number of lines below the cursor at EOF is one less than the number of lines below the cursor elsewhere in the file. Attached is a video in which I move the cursor down one line at a time. You'll notice that when moving from line 84 to line 85, instead of the view shifting, the cursor moves down, leaving only 9 lines below the cursor instead of 10.

https://github.com/Aasim-A/scrollEOF.nvim/assets/12166320/e09069d2-4d4a-4e93-ae01-f4cae9239715

**Comment by Aasim-A** [comment]
Hey @DanielPower, sorry for the late reply. I couldn't replicate the issue, can you update the plugin to the latest version and see if the issue still persists?

**Comment by PietHelzel** [comment]
I too have this exact issue, on the latest version

**Comment by Aasim-A** [comment]
Can you share your:
* neovim version
* scrolloff value
* plugin config
* sample text to reproduce the issue

**Comment by PietHelzel** [comment]
- Neovim Version: 0.9.4
- scrolloff value: Tried 4, 5 and 6, happens for all of them
- Plugin config (using lazy.nvim plugin manager): 

```lua
return {
    "Aasim-A/scrollEOF.nvim",
    config = function ()
        vim.o.scrolloff = 4
        require("scrollEOF").setup({
            insert_mode = true
        })
    end
}
```

- Sample text: Now this is where it gets weird. It seems to happen with any text (just a bunch of newlines for example, enough to fill your screen at least), but only if an LSP is attached to it. In a normal text file it doesn't happen, but it happens with a Java file or a Lua file with the LSP attached. Removing the LSP for either of those files makes it work like intended. Not sure what to make of this. If there's any more I can do to help, I'll be happy to do that.

**Comment by Aasim-A** [comment]
Given your config, and the things you've mentioned about the lsp, I couldn't replicate the issue. My neovim version is : 
```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1696795921
```

I tried it on a lua file with/without the lsp, and for both normal and insert mode. Maybe there is another plugin that is causing the issue?

Try to disable all of the other plugins then give it a try, if it works, enable lsp and try it one more time.
 
A quick way to do this using lazy is to create a new directory and tell lazy to look for plugins in that directory. Then you place the plugins that you want to enable in the newly created directory.

**Comment by PietHelzel** [comment]
You were right! Disabling Lspsaga solves it for me. @DanielPower are you by chance using Lspsaga too? @Aasim-A any idea what could be the cause?

**Comment by DanielPower** [comment]
I could reproduce the issue on any file without LspSaga. But I've determined the cause, and will provide a minimal reproduction config.

It seems that the off by one error occurs whenever `vim.opt.winbar` is in use. Perhaps ScrollEOF is not correctly considering the winbar when calculating the height of the window.

Reproduction config:
```
vim.opt.scrolloff = 10
vim.opt.winbar = "Hello World"

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
  "Aasim-A/scrollEOF.nvim",
  config = function()
    require("scrollEOF").setup()
  end,
})
```

**Comment by PietHelzel** [comment]
This checks out, as I was using the breadcrumbs feature in Lspsaga, which occupies the winbar.

**Comment by DanielPower** [comment]
I created a PR to address this: https://github.com/Aasim-A/scrollEOF.nvim/pull/10

ScrollEOF was using `vim.api.nvim_get_window_height(0)` to get window height. This function returns the outer height of the window (including winbar). I switched to using `vim.fn.winheight(0)`, which returns the inner height.

If you can, please test if this solves the issue for you with LspSaga and breadcrumbs enabled.

**Comment by PietHelzel** [comment]
@DanielPower I tested your version and it works great!

**Comment by Aasim-A** [comment]
Thanks guys! The new version is now live.
